name: 'CI: Build'
run-name: Execute ${{ inputs.command }} for initialization and build ${{ github.ref_name }}__${{ github.sha }}.zip

on:
  workflow_dispatch:
    inputs:
      command:
        description: "The command to run"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

env:
  AWS_REGION: us-east-1
  GIT_ORGANIZATION_NAME: ${{ github.repository_owner }}
  TG_DIR: "live/aws/_initializations/${{ github.event.repository.name }}"
  BUILD_ID: ${{ github.ref_name }}__${{ github.sha }}.zip

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    outputs:
      build_id: ${{ steps.ci.outputs.build_id }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/actions/ci
        name: Run CI Action
        id: ci
        with: 
          CLOUD_DEPLOYMENT_PAT: ${{ secrets.CLOUD_DEPLOYMENT_PAT }}
          DASHG_CLOUD_PLATFORM_PAT: ${{ secrets.DASHG_CLOUD_PLATFORM_PAT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}
          GIT_ORGANIZATION_NAME: ${{ env.GIT_ORGANIZATION_NAME }}
          TG_SOURCE: ${{ env.TG_INIT_SOURCE }}
          TG_DIR: ${{ env.TG_INIT_DIR }}
          TG_COMMAND: ${{ inputs.command }}